My About Page
uclaacm/teach-la-website pull request #121
Opened 2020-10-20 05:44 UTC by ethanieltoe

This is my about page and my image

2020-10-20 07:30 UTC, malsf21 requested changes
Hey Ethan! Thank you for making your first pull request to the repository! 

I left some feedback on your team page - there are a few configuration options missing/that need fixing for your page to build properly. Do you mind resolving those - I can get back to you and then merge your PR!

2020-10-20 07:30 UTC, malsf21 commented on _team/Eto.md
> +group: "Member"
This should be `"member"` for things to render properly!

2020-10-20 07:30 UTC, malsf21 commented on _team/Eto.md
> +img: "me.jpg"
Do you mind renaming this and the file to a more descriptive name such as `"eto.jpg"`? It will help with name collisions in the future!

2020-10-20 07:30 UTC, malsf21 commented on _team/Eto.md
> +---
Do you mind adding a `graduating_year` key-value pair?

2020-10-21 02:05 UTC, ethanieltoe commented
Okay I've resolved the changes but do I need to make a new pull request with the updated files?

2020-10-21 06:19 UTC, malsf21 approved these changes
Hm, in the interest of time I resolved a few of the other errors:

* you were missing a space between `:"`
* the image was in the wrong folder
* the image wasn't cropped or square

That's okay though, hopefully we can now merge this and get you started on some more work. Thanks for the PR Ethan!

2020-10-21 06:50 UTC, merged