Adding Fair ML Speaker Series Page + General Speaker Series Page
uclaacm/teach-la-website pull request #174
Opened 2020-12-04 08:45 UTC by a17ung

I had trouble adding a new CSS file specific for the page so I ended up using a combo of HTML styles and _citylab.scss (def want to change later). I also created a new page for the speaker series because I thought it'd be nice to have a directory for when they complete more events! Said page is definitely not done but I'm going to work on it in the next few days or so. Still not sure about the layout/amount of info on the page as well.

2020-12-05 18:44 UTC, malsf21 requested changes
Hey Amanda,

Thanks for your work on this so far, the page is looking great! Left a few points of feedback; here's the general gist:

* I think you may have accidentally messed up a few files on the merge that make your team page entry not work properly! 
* In terms of copy and content, you may want to revise how we're framing it with the team - feel free to send the draft preview of the PR to the channel. I think Arjun may have some specific asks in particular
* Left some minor comments on reusable CSS (when possible, you should avoid the style tag unless you have a good reason to use it). 

Also, to answer your question on adding a new .scss file, it's a two-step process!

1. first, add your `_whatever.scss` file in the `_sass` folder
2. next, you'll need to import your new file in `css/main.scss` - as long as the `@import` statement is under variables and basics, everything should work as intended!

This is looking great for a first iteration! If you're able to knock out most of the feedback, I think all that's probably left is some minor copy changes; then, it'll be good to merge!

2020-12-05 18:44 UTC, malsf21 commented on _team/aung.md.orig
> +---
Is this file an artefact from the merge conflict? I don't think we should merge it into `master`

2020-12-05 18:44 UTC, malsf21 commented on events/fair-ml.html
> +			<li> <a class = "tla-link" href="https://slack-files.com/files-pri-safe/TA3824MMX-F01BCVAJZ6X/fairness-ethics-in-ai-talk.pdf?c=1607066003-e8f6a1cc96e00768" target = "_blank" rel = "noopener norefe
I wouldn't personally use a Slack link to share a file - let's instead 

* link to the slides on Catherine's website (if they're there, this is the preferred option - we should give credit)
* make a copy and put it in the site itself 
* share a google drive link

2020-12-05 18:44 UTC, malsf21 commented on events/fair-ml.html
> +		<p style = "font-size: 115%;">
In general, I would avoid using inline style tags when possible - we should define this as a class somewhere (maybe in `_basics.scss`)

2020-12-05 18:44 UTC, malsf21 commented on events/fair-ml.html
> +		<ul style = "font-size: 150%;">
We've already defined a class that does this (or something similar) - `.text-15x`!

2020-12-05 18:44 UTC, malsf21 commented on events/fair-ml.html
> +</p>
I think this content should instead generally explain what the Fair ML speaker series is. You don't necessarily have to write the copy - feel free to reach out to someone in the slack channel for help on this!

2020-12-05 18:44 UTC, malsf21 commented on events/fair-ml.html
> +<div class="citylab-section" style = "margin-top: 2em;">
I would maybe swap the order of this section and the predictive policing one - from a framing perspective, this is a "more resources"/credits type of content block, while the other is the main content. We can also discuss how to revise the copy later!

2020-12-05 18:44 UTC, malsf21 commented on events/fair-ml.html
> +		<img class = "img-responsive" src = "{{site.baseurl}}/img/undraw/content.svg" alt = "drawing related to content" />
A slightly more descriptive alt tag would be nice!

2020-12-05 18:44 UTC, malsf21 commented on events/fair-ml.html
> +		https://docs.google.com/document/d/1f1XhxGFxA-JAz2Dw6I5gy5jS2Z_oW3aBKmJUkU5PBqA/edit" target="_blank" rel="noopener noreferrer"><span class = "fa fa-link"> </span> Link to ML Wiki</a>
Nitpicky, but a different Icon here might be nice! Something that feels more "wiki-ish"

2020-12-05 18:44 UTC, malsf21 commented on events/fair-ml.html
> +		https://docs.google.com/presentation/d/1IRvK3awKEll42cs8MTc3YdCONHa4E_3hV-dU2inlGQ8/edit#slide=id.g9fdeae80bb_0_18" target ="_blank" rel = "noopener noreferrer"><span class = "fa fa-link"></span> L
Nitpicky, but a different Icon here might be nice! Something that feels more "presentation"/"case-study"-ish. You can find the list of free font awesome icons at [the FA5 website](https://fontawesome.com/icons?d=gallery)

2020-12-05 18:44 UTC, malsf21 commented on events/fair-ml.html
> +		https://docs.google.com/presentation/d/1IRvK3awKEll42cs8MTc3YdCONHa4E_3hV-dU2inlGQ8/edit#slide=id.g9fdeae80bb_0_18" target ="_blank" rel = "noopener noreferrer"><span class = "fa fa-link"></span> L
Minor formatting, but is there a reason that this line break is here?

2020-12-05 18:44 UTC, malsf21 commented on _team/aung.md
>  img: "aung.jpg"
Think you accidentally deleted the old image and kept the artifact (`aung.jpg.orig`) - you may want to revert that so your team page works!

2020-12-05 18:44 UTC, malsf21 commented on speaker-series.html
> +<h1 class="title page-title"> Speaker Series </h1>
For now we can delete this page, maybe we'll revisit it another time!

2021-01-16 00:43 UTC, malsf21 commented
Going to take over this as Amanda takes a quick break from the dev team!

2021-01-16 08:37 UTC, malsf21 commented
Just wrapped up Amanda's changes, and adding some things since the ticket was assigned. Here's a complete diff from master:

* created a new "AI Ethics Speaker Series" page; links to it from the footer
* writes out AI Ethics content for four categories + thanks to Catherine (hosting her slides, since they're not on her website)
* refactors `_citylab.scss` into `_event.scss` for shared utilities; renames `.citylab-*` classes to `.event-*`
* adds `.border-ai` utility class
* **importantly, applies `*{ box-sizing: border-box;}`. this has unintended side effects to the rest of the site**
* updates Amanda's profile card

2021-01-16 08:38 UTC, malsf21 commented
Because this change has quite a few side effects, going to ask for a double-review on these changes!

2021-01-17 00:23 UTC, lishamohan reviewed
Looks good to me! Only notable differences I noticed from changing the box-sizing is that the "join us" button got a lil squashed and the pictures on the team page are smaller. Both can be fixed real quick; lmk if you want me to make a quick commit to fix them (i would just suggest the changes on this PR but i don't think i can since those files weren't edited in this PR)

2021-01-17 01:08 UTC, malsf21 commented
> Only notable differences I noticed from changing the box-sizing is that the navbar "join us" button got a lil squashed and the pictures on the team page are smaller.

Great catch, I noticed the navbar button but not the team page issues! Feel free to add on to this branch if you want 😊  (but also I can do it if you're busy)!

2021-01-17 01:48 UTC, lishamohan commented
Okay there we go I think that should do it!

2021-01-17 01:51 UTC, malsf21 commented
> Okay there we go I think that should do it!

Can verify that your changes work as intended, thanks for the quick fix! Just waiting on Leo's feedback then 😊

2021-01-21 08:05 UTC, malsf21 commented
Pinging @krashanoff again on this for a second look!

2021-01-21 08:31 UTC, krashanoff approved these changes
Quite a many changes, but after looking through the styles, it looks good to me. Refactors make sense and the page looks good. Thanks for adding this all Amanda, thanks for the fix after the `border-box` change Lisha, and thanks for the thorough review Matt!

2021-01-21 08:42 UTC, merged