creates a resources for new developers page
uclaacm/teach-la-website pull request #257
Opened 2021-02-11 23:03 UTC by ldalton02

2021-02-12 05:18 UTC, malsf21 requested changes
Just to sum up what we talked about at today's dev team meeting:

* I can handle the copy - don't worry about that
* if you can, please create a clear visual difference from video/written resources and template/library code!
* to fix the mobile responsiveness issues, I suggest you try using media queries and display grid; [here's an example using the event.scss](https://github.com/uclaacm/teach-la-website/blob/master/_sass/_event.scss) code

2021-02-18 02:11 UTC, malsf21 commented
Just checking in - not sure if you've seen yet @ldalton02, but I think there were some issues resolving the merge conflict and thus the site won't build. Also, is there a reason there are a lot of whitespace changes with this PR?

2021-02-19 06:44 UTC, mattxwang requested changes
Hey Luke,

Thanks for resolving the merge issues. Just some thoughts:

* there seems to be a lot of extraneous CSS - is every property needed in each of these cases? I think there's quite a bit of flex-stuff in particular (ex all the `align-items`) that's not needed; the most flex you'd need is probably just a vertical centering solution.
* left some other comments on CSS duplication
* remember that for links, `"here"` is not very accessible text; instead, try using something like 

```html
Browse <a class="tla-link" href="...">the documentation<a/> for more information.
```

You may also want to use `rel="noopener noreferrer"` for external links.

Thanks for your revisions so far! After this round, I can update the copy and then we'll be good to merge.

(p.s. I may also change the path and/or the footer)

2021-02-19 06:44 UTC, mattxwang commented on _sass/_basic.scss
> +}
This is a duplicate class - we already have `.text-center`!

2021-02-19 06:44 UTC, mattxwang commented on _sass/_basic.scss
> +}
Do you use this class?

2021-02-19 06:44 UTC, mattxwang commented on devresources.html
> +<div class="container container-fill container-restricted">
This already gets applied by the default layout, you don't need to add it again

2021-02-19 06:44 UTC, mattxwang commented on _sass/_basic.scss
> +    box-sizing: border-box;
This is already set by default

2021-02-19 06:44 UTC, mattxwang commented on _sass/_basic.scss
> +    box-sizing: border-box;
Also already set my default

2021-02-19 06:44 UTC, mattxwang commented on _sass/_basic.scss
> +    }
This media query seems like it doesn't do anything?

2021-02-21 01:58 UTC, mattxwang requested changes
Just a few other notes, and then I'll do the copy-pass and we'll merge!

2021-02-21 01:58 UTC, mattxwang commented on _sass/_basic.scss
> +}
I think this is still duplicated with `.text-center`!

2021-02-21 01:58 UTC, mattxwang commented on _sass/_basic.scss
> +}
I think this class isn't necessary - you can instead add padding to the parent container?

2021-02-23 07:50 UTC, mattxwang reviewed
Thanks for the quick changes Luke! Looks good in general, I'll review the copy and then give you the go-ahead to merge once I get a chance to do that!

2021-02-24 06:07 UTC, mattxwang commented
Note to self: also need to merge master into this to reflect #268.

2021-03-06 07:24 UTC, mattxwang approved these changes
Okay, made some content revisions. I think we're good to merge - Luke, you can do the honours, please squash and merge!

2021-03-06 08:55 UTC, merged