Intern page
uclaacm/teach-la-website pull request #342
Opened 2021-05-06 02:25 UTC by vivianha534

**New files**
- Added intern page that has information about the Teach LA internship program

**Changed files**
- updated footer to include intern page
- updated join page to include a section about the internship program

2021-05-09 00:08 UTC, vivianha534 commented
#342

2021-05-09 00:45 UTC, reginawang99 requested changes
sick :)) just some nits!!

2021-05-09 00:45 UTC, reginawang99 commented on intern.html
> +        Teach LA’s internship program gives interns the opportunity to take on more responsibility within the club, while simultaneously receiving mentorship and guidance from current officers. Inter
nit: idk if we do this in the tla page, but when the string is this long, it's really hard for devs to read it in their VSCode or whatever!

(tldr add enters so that string isn't too hard to read, same with other lines in the PR)

feel free to dismiss!

2021-05-09 00:45 UTC, reginawang99 commented on intern.html
> +<div class="what-is-intern-container">
nit: maybe we can use something we already have? anything is good tho!
```suggestion
<div class="row-desktop row-desktop-ratio-1-2 row-desktop-reverse">
```

2021-05-09 00:45 UTC, reginawang99 commented on intern.html
> +<div class="what-is-intern-container">
might need to swap the `p` tag and the `img` tag for this to work :)

2021-05-09 00:45 UTC, reginawang99 commented on intern.html
> +        Teach LA’s internship program gives interns the opportunity to take on more responsibility within the club, while simultaneously receiving mentorship and guidance from current officers. Inter
also, the blobs of text on the page kinda make it hard to read :(( maybe we can add new lines between things at least?(and possibly links and stuffs?) idk tho your choice!

2021-05-09 00:45 UTC, reginawang99 commented on intern.html
> +
```suggestion
```

2021-05-09 00:45 UTC, reginawang99 commented on _sass/_interns.scss
> +}
i dont think this is used anywhere?

2021-05-09 00:45 UTC, reginawang99 commented on join.html
> +            </ul>
IMO i think this is getting kinda long/messy, can we maybe just have the top one and have a link to past internship projects (which i think you are doing rn)? idk your choice tho!

2021-05-09 00:45 UTC, reginawang99 commented on join.html
> +
```suggestion
```

2021-05-10 06:40 UTC, vivianha534 commented
@reginawang99 added a couple more things (and took some stuff away) to the intern page to make it a little more readable.

**Changes**
- listed out difference between gen mems and interns
- added more images 
- removed some points about the intern program from join page

2021-05-11 04:56 UTC, reginawang99 approved these changes
LGTM!! 🥳 

(i have some small typos/punctuations if you might want to fix tho!)

2021-05-11 04:56 UTC, reginawang99 commented on intern.html
> +    To find out more about how you can join us as a general member check out our
```suggestion
    To find out more about how you can join us as a general member, check out our 
```

2021-05-11 08:57 UTC, vivianha534 commented
closes #342

2021-05-11 08:58 UTC, merged

2021-05-11 08:59 UTC, vivianha534 commented
closes #342